#!/bin/bash
mv /tmp/wms.config.json /var/www/wms/config/wms.config.json -f &>/dev/null
sudo chown www:www /var/www/wms -R
if ! cat /etc/sudoers | grep -q codesys_restart.sh ; then
    sudo sed -i '/www ALL=NOPASSWD:/s/$/, \/home\/codesys_root\/PlcLogic\/codesys_restart.sh/' /etc/sudoers
fi
while ! sudo /etc/init.d/lighttpd reload &> /dev/null ; do
    :
done
exit 0

